ERROR Internal Server Error: /fortunes
Traceback (most recent call last):
  File "/home/tfb/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/Django-1.6b2-py2.7.egg/django/core/handlers/base.py", line 114, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/tfb/FrameworkBenchmarks/django/hello/world/views.py", line 56, in fortunes
    return render(request, 'fortunes.html', context)
  File "/home/tfb/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/Django-1.6b2-py2.7.egg/django/shortcuts/__init__.py", line 53, in render
    return HttpResponse(loader.render_to_string(*args, **kwargs),
  File "/home/tfb/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/Django-1.6b2-py2.7.egg/django/template/loader.py", line 162, in render_to_string
    t = get_template(template_name)
  File "/home/tfb/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/Django-1.6b2-py2.7.egg/django/template/loader.py", line 138, in get_template
    template, origin = find_template(template_name)
  File "/home/tfb/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/Django-1.6b2-py2.7.egg/django/template/loader.py", line 131, in find_template
    raise TemplateDoesNotExist(name)
TemplateDoesNotExist: fortunes.html
ERROR Internal Server Error: /fortunes
Traceback (most recent call last):
  File "/home/tfb/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/Django-1.6b2-py2.7.egg/django/core/handlers/base.py", line 114, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/tfb/FrameworkBenchmarks/django/hello/world/views.py", line 56, in fortunes
    return render(request, 'fortunes.html', context)
  File "/home/tfb/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/Django-1.6b2-py2.7.egg/django/shortcuts/__init__.py", line 53, in render
    return HttpResponse(loader.render_to_string(*args, **kwargs),
  File "/home/tfb/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/Django-1.6b2-py2.7.egg/django/template/loader.py", line 162, in render_to_string
    t = get_template(template_name)
  File "/home/tfb/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/Django-1.6b2-py2.7.egg/django/template/loader.py", line 138, in get_template
    template, origin = find_template(template_name)
  File "/home/tfb/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/Django-1.6b2-py2.7.egg/django/template/loader.py", line 131, in find_template
    raise TemplateDoesNotExist(name)
TemplateDoesNotExist: fortunes.html
curl: (22) The requested URL returned error: 500
